/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;


import Datos.ConectarBd;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author codefutura
 */
public final class FrmConexionDB extends javax.swing.JDialog {

    /**
     * Creates new form FrmConexionDB
     * @param parent
     * @param modal
     */
    private boolean guarda;
    public FrmConexionDB(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        leerArch();
    }

   private void setGuarda(boolean gd){
        guarda=gd;
   } 
   
   public boolean getGuarda(){
       return guarda;
   }
   
   public void leerArch() {
        File archivo;
        archivo= new File("database.properties");      
          if(archivo.exists()==false){
                return;
        }    
        try {
            Properties pro;
            pro = new Properties();
            pro.load(new FileReader("database.properties"));
            tBaseDatos.setText(pro.getProperty("db.database"));
            tClave.setText(pro.getProperty("db.clave"));
            tPuerto.setText(pro.getProperty("db.puerto"));
            tUser.setText(pro.getProperty("db.usuario"));
            tServidor.setText(pro.getProperty("db.ip")); 
           
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmConexionDB.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FrmConexionDB.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FrmConexionDB.class.getName()).log(Level.SEVERE, null, ex);
        }    
  }
   
   public void crearFichero(String datos, String senda) {
        try{ 
            FileWriter fw   = new FileWriter(senda, false);
            fw.close(); 
        } catch (IOException e) {
		    JOptionPane.showMessageDialog(this, "Error Al registrar la conexion "+e.getMessage()); }
    }
    
    public void setFichero() {
        try {
            File archivo;
            archivo= new File("database.properties");      
            if(archivo.exists()==false){
                 crearFichero("" ,"database.properties");
            }
            Properties pro;
            pro = new Properties();
            pro.load(new FileReader("database.properties"));
            pro.setProperty("db.database", tBaseDatos.getText());
            pro.setProperty("db.clave", String.valueOf(tClave.getPassword()));
            pro.setProperty("db.puerto", tPuerto.getText());
            pro.setProperty("db.usuario", tUser.getText());
            pro.setProperty("db.ip", tServidor.getText());
            pro.store(new FileWriter("database.properties"), "Configuracion base de datos");
            pro=null;
                     
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmConexionDB.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FrmConexionDB.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tbnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        tBaseDatos = new javax.swing.JTextField();
        tServidor = new javax.swing.JTextField();
        tPuerto = new javax.swing.JTextField();
        tUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tClave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Establecer conexión con la base de datos");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setText("Servidor");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Base de datos");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Puerto");

        tbnGuardar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tbnGuardar.setForeground(new java.awt.Color(101, 69, 3));
        tbnGuardar.setText("Conectar y guardar");
        tbnGuardar.setToolTipText("");
        tbnGuardar.setContentAreaFilled(false);
        tbnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbnGuardar.setFocusPainted(false);
        tbnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(101, 69, 3));
        btnCancelar.setText("Cancelar");
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tBaseDatos.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tBaseDatos.setForeground(new java.awt.Color(0, 51, 204));
        tBaseDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tServidor.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tServidor.setForeground(new java.awt.Color(0, 51, 204));
        tServidor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tPuerto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tPuerto.setForeground(new java.awt.Color(0, 51, 204));
        tPuerto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tUser.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tUser.setForeground(new java.awt.Color(0, 51, 204));
        tUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("Usuario");

        tClave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tbnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tPuerto)
                        .addGap(165, 165, 165))
                    .addComponent(tServidor, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(tBaseDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(tUser, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(tClave))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tBaseDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tUser)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(tClave, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnGuardarActionPerformed
    
    if(String.valueOf(tClave.getPassword()).isEmpty()){
        JOptionPane.showMessageDialog(this,"Ingresa la contraseña");
        tClave.requestFocus();
        return;
    }
        
    String datos=(new StringBuilder()).append(tServidor.getText()).append(";")
            .append(tBaseDatos.getText()).append(";").append(String.valueOf(tClave.getPassword()))
            .append(";").append(tPuerto.getText()).append(";")
            .append(tUser.getText()).toString();
    
    ConectarBd conex =new ConectarBd(0);
    if(conex.probarConexion(tServidor.getText(),tBaseDatos.getText(),tPuerto.getText(),tUser.getText(),String.valueOf(tClave.getPassword()),this)==true){
           JOptionPane.showMessageDialog(this,"Conexion exitosa");
       }else{
        return;
    }
    setGuarda(true);
    setFichero(); 
    ConectarBd.asignarParametrosCon(tServidor.getText(),tBaseDatos.getText(), tPuerto.getText(), tUser.getText(), String.valueOf(tClave.getPassword()));
    dispose();
    
    }//GEN-LAST:event_tbnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       setGuarda(false);
       System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tBaseDatos;
    private javax.swing.JPasswordField tClave;
    private javax.swing.JTextField tPuerto;
    private javax.swing.JTextField tServidor;
    private javax.swing.JTextField tUser;
    private javax.swing.JButton tbnGuardar;
    // End of variables declaration//GEN-END:variables
}
