
package Presentacion;

import Datos.DbCxc;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author codefutura
 */
public class FrmMenuCxc extends javax.swing.JDialog {

    /**
     * Creates new form FrmMenuCxc
     * @param parent
     * @param modal
     */
    public FrmMenuCxc(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpGrigCxc = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnNuevo2 = new javax.swing.JButton();
        btnModificar2 = new javax.swing.JButton();
        btnEliminar2 = new javax.swing.JButton();
        btnRecibo = new javax.swing.JButton();
        tBuscar = new javax.swing.JTextField();
        btnBuscar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpGrigCxc.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Fecha", "Nombre", "Importe", "Pago", "Balance", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(22);
        jTable1.setSelectionForeground(new java.awt.Color(0, 51, 255));
        jScrollPane1.setViewportView(jTable1);

        jpGrigCxc.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnNuevo2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnNuevo2.setText("Nuevo");
        btnNuevo2.setContentAreaFilled(false);
        btnNuevo2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo2.setFocusPainted(false);
        btnNuevo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo2.setMaximumSize(new java.awt.Dimension(87, 61));
        btnNuevo2.setMinimumSize(new java.awt.Dimension(87, 61));
        btnNuevo2.setPreferredSize(new java.awt.Dimension(87, 61));
        btnNuevo2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo2ActionPerformed(evt);
            }
        });

        btnModificar2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnModificar2.setText("Modificar");
        btnModificar2.setToolTipText("");
        btnModificar2.setContentAreaFilled(false);
        btnModificar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar2.setFocusPainted(false);
        btnModificar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar2ActionPerformed(evt);
            }
        });

        btnEliminar2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnEliminar2.setText("Eliminar");
        btnEliminar2.setContentAreaFilled(false);
        btnEliminar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar2.setFocusPainted(false);
        btnEliminar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar2.setMaximumSize(new java.awt.Dimension(87, 61));
        btnEliminar2.setMinimumSize(new java.awt.Dimension(87, 61));
        btnEliminar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar2ActionPerformed(evt);
            }
        });

        btnRecibo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnRecibo.setText("Registrar Pago");
        btnRecibo.setContentAreaFilled(false);
        btnRecibo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecibo.setFocusPainted(false);
        btnRecibo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRecibo.setMaximumSize(new java.awt.Dimension(87, 61));
        btnRecibo.setMinimumSize(new java.awt.Dimension(87, 61));
        btnRecibo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReciboActionPerformed(evt);
            }
        });

        tBuscar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        tBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBuscarActionPerformed(evt);
            }
        });
        tBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tBuscarKeyReleased(evt);
            }
        });

        btnBuscar2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnBuscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/binoculars.png"))); // NOI18N
        btnBuscar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnBuscar2.setContentAreaFilled(false);
        btnBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpGrigCxc, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevo2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)
                                .addComponent(btnRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpGrigCxc, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNuevo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRecibo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo2ActionPerformed
        // TODO add your handling code here:

        FrmCxc c = new FrmCxc(null, true, 0);
        c.setLocationRelativeTo(null);
        c.setVisible(true);
        if (c.isAceptada() == true) {
            limpiarTabla(jTable1);
            DbCxc.buscarPorNombre((DefaultTableModel) jTable1.getModel(), tBuscar.getText(), this);
            tBuscar.setText("");
        }

        c = null;
        System.gc();
    }//GEN-LAST:event_btnNuevo2ActionPerformed

    private void btnModificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar2ActionPerformed

        if (jTable1.getSelectedRow() >= 0) {
            Integer codigoCxp;
            if (jTable1.getSelectedRowCount() > 0) {
                codigoCxp = Integer.parseInt(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0)));
                FrmCxc mCxc = new FrmCxc(null, true, codigoCxp);
                mCxc.mostrarCxp(codigoCxp);
                mCxc.setTitle("Actualización...");
                mCxc.setLocationRelativeTo(null);
                mCxc.setVisible(true);
                if (mCxc.isAceptada() == true) {
                    limpiarTabla(jTable1);
                    DbCxc.buscarPorNombre((DefaultTableModel) jTable1.getModel(), "", this);
                    tBuscar.setText("");
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "No hay ningún registro seleccionado ...");
        }
    }//GEN-LAST:event_btnModificar2ActionPerformed

    private void btnEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar2ActionPerformed
        // TODO add your handling code here:

        if (JOptionPane.showConfirmDialog(this, "Estas seguro que deseas eliminar la cuenta seleccionado...",
                "Eliminar cuenta por cobrar...", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            DbCxc.EliminarCxc(id);
            DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
            mod.removeRow(jTable1.getSelectedRow());

        }
    }//GEN-LAST:event_btnEliminar2ActionPerformed

    private void btnReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReciboActionPerformed
 
    }//GEN-LAST:event_btnReciboActionPerformed

    private void tBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBuscarActionPerformed

    }//GEN-LAST:event_tBuscarActionPerformed

    private void tBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tBuscarKeyReleased

        // TODO add your handling code here:
        if (jTable1.getRowCount() > 0) {
            limpiarTabla(jTable1);
        }

        DbCxc.buscarPorNombre((DefaultTableModel) jTable1.getModel(), tBuscar.getText(), this);
    }//GEN-LAST:event_tBuscarKeyReleased

    private void btnBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar2ActionPerformed
        // TODO add your handling code here:

        if (jTable1.getRowCount() > 0) {
            limpiarTabla(jTable1);
        }
        DbCxc.buscarPorNombre((DefaultTableModel) jTable1.getModel(), tBuscar.getText(), this);
    }//GEN-LAST:event_btnBuscar2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar2;
    private javax.swing.JButton btnEliminar2;
    private javax.swing.JButton btnModificar2;
    private javax.swing.JButton btnNuevo2;
    private javax.swing.JButton btnRecibo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpGrigCxc;
    private javax.swing.JTextField tBuscar;
    // End of variables declaration//GEN-END:variables

    public void limpiarTabla(JTable tabla) {
        try {
            DefaultTableModel model = (DefaultTableModel) tabla.getModel();
            int filas = tabla.getRowCount();
            for (int i = 0; filas > i; i++) {
                model.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al limpiar la tabla.");
        }
    }

}
