package Presentacion;

/**
 *
 * @author codefutura
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnEstudiante = new javax.swing.JButton();
        btnCursos = new javax.swing.JButton();
        btnNotas = new javax.swing.JButton();
        btnCxc = new javax.swing.JButton();
        btnNomina = new javax.swing.JButton();
        btnParametros = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Luz del Futuro, sistema de gestión de colegios");
        setPreferredSize(new java.awt.Dimension(800, 600));

        jToolBar1.setRollover(true);

        btnEstudiante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/students.png"))); // NOI18N
        btnEstudiante.setText("Estudiantes");
        btnEstudiante.setBorderPainted(false);
        btnEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEstudiante.setFocusable(false);
        btnEstudiante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEstudiante.setMaximumSize(new java.awt.Dimension(96, 81));
        btnEstudiante.setMinimumSize(new java.awt.Dimension(96, 81));
        btnEstudiante.setOpaque(false);
        btnEstudiante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudianteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEstudiante);

        btnCursos.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/classroom.png"))); // NOI18N
        btnCursos.setText("Cursos");
        btnCursos.setToolTipText("");
        btnCursos.setBorderPainted(false);
        btnCursos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCursos.setFocusable(false);
        btnCursos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCursos.setMaximumSize(new java.awt.Dimension(96, 81));
        btnCursos.setMinimumSize(new java.awt.Dimension(96, 81));
        btnCursos.setOpaque(false);
        btnCursos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCursos);

        btnNotas.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/student_calification.png"))); // NOI18N
        btnNotas.setText("Publicar Notas");
        btnNotas.setBorderPainted(false);
        btnNotas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNotas.setFocusable(false);
        btnNotas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNotas.setMaximumSize(new java.awt.Dimension(96, 81));
        btnNotas.setMinimumSize(new java.awt.Dimension(96, 81));
        btnNotas.setOpaque(false);
        btnNotas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNotas);

        btnCxc.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnCxc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pago.png"))); // NOI18N
        btnCxc.setText("Recibo");
        btnCxc.setToolTipText("");
        btnCxc.setBorderPainted(false);
        btnCxc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCxc.setFocusable(false);
        btnCxc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCxc.setOpaque(false);
        btnCxc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCxc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCxcActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCxc);

        btnNomina.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnNomina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calcu.png"))); // NOI18N
        btnNomina.setText("Nomina");
        btnNomina.setBorderPainted(false);
        btnNomina.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNomina.setFocusable(false);
        btnNomina.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNomina.setMaximumSize(new java.awt.Dimension(96, 81));
        btnNomina.setMinimumSize(new java.awt.Dimension(96, 81));
        btnNomina.setOpaque(false);
        btnNomina.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNominaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNomina);

        btnParametros.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnParametros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/support.png"))); // NOI18N
        btnParametros.setText("Parametros");
        btnParametros.setBorderPainted(false);
        btnParametros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnParametros.setFocusable(false);
        btnParametros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnParametros.setMaximumSize(new java.awt.Dimension(96, 81));
        btnParametros.setMinimumSize(new java.awt.Dimension(96, 81));
        btnParametros.setOpaque(false);
        btnParametros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParametrosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnParametros);

        btnSalir.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/door50.png"))); // NOI18N
        btnSalir.setText("S a l i r");
        btnSalir.setBorderPainted(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setMaximumSize(new java.awt.Dimension(96, 81));
        btnSalir.setMinimumSize(new java.awt.Dimension(96, 81));
        btnSalir.setOpaque(false);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalir);

        jPanel1.setBackground(new java.awt.Color(87, 140, 186));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/colegio-logo.png"))); // NOI18N

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(104, 156, 201), 1, true));
        jPanel2.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(191, 210, 224));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Luz del Futuro");
        jLabel1.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tel.:809-584-3601");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("E-mail.: luzdelfuturo@gmail.com");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(142, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudianteActionPerformed
        FrmListaEstudiantes mEstudiante = new FrmListaEstudiantes(this, true);
        mEstudiante.setLocationRelativeTo(this);
        mEstudiante.setVisible(true);
    }//GEN-LAST:event_btnEstudianteActionPerformed

    private void btnCxcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCxcActionPerformed
        FrmMenuCxc cxc = new FrmMenuCxc(this, true);
        cxc.setLocationRelativeTo(this);
        cxc.setVisible(true);
    }//GEN-LAST:event_btnCxcActionPerformed

    private void btnCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursosActionPerformed
        FrmRegistroCurso curso = new FrmRegistroCurso(this, true);
        curso.setLocationRelativeTo(null);
        curso.setVisible(true);
    }//GEN-LAST:event_btnCursosActionPerformed

    private void btnNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasActionPerformed
        FrmPublicarNotas publicar = new FrmPublicarNotas(this, true);
        publicar.setLocationRelativeTo(this);
        publicar.setVisible(true);
    }//GEN-LAST:event_btnNotasActionPerformed

    private void btnParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParametrosActionPerformed
        FrmMenuParametro par = new FrmMenuParametro(this, true);
        par.setLocationRelativeTo(this);
        par.setVisible(true);

    }//GEN-LAST:event_btnParametrosActionPerformed

    private void btnNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNominaActionPerformed
        FrmMenuNomina nomina = new FrmMenuNomina(this, true);
        nomina.setLocationRelativeTo(this);
        nomina.setVisible(true);
    }//GEN-LAST:event_btnNominaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCursos;
    private javax.swing.JButton btnCxc;
    private javax.swing.JButton btnEstudiante;
    private javax.swing.JButton btnNomina;
    private javax.swing.JButton btnNotas;
    private javax.swing.JButton btnParametros;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
