package Presentacion;

import Datos.DbCurso;
import Datos.DbEstudiante;
import Datos.dbAsignatura;
import Negocio.Curso;
import Negocio.FormatoFecha;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author alexa
 */
public class FrmRegistroCurso extends javax.swing.JDialog {

    private int idDocente;
    Curso c = new Curso();
    DbCurso dc = new DbCurso();

    /**
     * Creates new form frmRegistroCurso
     *
     * @param parent
     * @param modal
     */
    public FrmRegistroCurso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if (c.getId_curso() == 0) {
            tFecha.setDate(new Date());
            int anio = FormatoFecha.getAnio(tFecha);
            tAnio.setText(String.valueOf(anio + "-" + (anio + 1)));
            //Cargar las asignaturas sin registrar en curso
            cargarAsignaturas();
        } else {
            cargarAsignaturaDelCuso(c.getId_curso());
        }

        formatoRejilla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTitulo = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tAula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbTanda = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tFecha = new com.toedter.calendar.JDateChooser();
        btnEliminarSeleccionado3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbGrado = new javax.swing.JComboBox<>();
        jTabCurso = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jspDatos = new javax.swing.JScrollPane();
        jTableEstudiante = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAsignatura = new javax.swing.JTable();
        btnRetirar1 = new javax.swing.JButton();
        btnAgregar1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tCapacidad = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        tNombreDocente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tAnio = new javax.swing.JTextField();
        btnDocente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnTitulo.setBackground(new java.awt.Color(205, 97, 85));

        lbTitulo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Registro de Curso");
        lbTitulo.setToolTipText("");

        javax.swing.GroupLayout pnTituloLayout = new javax.swing.GroupLayout(pnTitulo);
        pnTitulo.setLayout(pnTituloLayout);
        pnTituloLayout.setHorizontalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTituloLayout.setVerticalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Aula");

        tAula.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tAula.setForeground(new java.awt.Color(0, 51, 255));
        tAula.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Tanda");

        cbTanda.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbTanda.setForeground(new java.awt.Color(0, 51, 255));
        cbTanda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutina", "Vespertina" }));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Inicio");

        tFecha.setDateFormatString("dd-MM-yyyy");
        tFecha.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tFechaComponentAdded(evt);
            }
        });
        tFecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tFechaPropertyChange(evt);
            }
        });
        tFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFechaKeyReleased(evt);
            }
        });

        btnEliminarSeleccionado3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnEliminarSeleccionado3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete_1.png"))); // NOI18N
        btnEliminarSeleccionado3.setText("Cancelar");
        btnEliminarSeleccionado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSeleccionado3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Grado");

        cbGrado.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbGrado.setForeground(new java.awt.Color(0, 51, 255));
        cbGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nivel Inicial", "Primario", "Secundario" }));

        jTabCurso.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTabCurso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabCursoStateChanged(evt);
            }
        });
        jTabCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabCursoMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(124, 152, 179));

        jTableEstudiante.setBackground(new java.awt.Color(234, 250, 241));
        jTableEstudiante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTableEstudiante.setForeground(new java.awt.Color(15, 15, 168));
        jTableEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "id_curso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEstudiante.setGridColor(new java.awt.Color(0, 51, 255));
        jTableEstudiante.setOpaque(false);
        jTableEstudiante.setRowHeight(20);
        jspDatos.setViewportView(jTableEstudiante);

        btnAgregar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnAgregar.setText("Inscribir");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnRetirar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lista de estudiantes inscrito");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspDatos)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(btnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRetirar)
                        .addComponent(btnAgregar))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
        );

        jTabCurso.addTab("Estudiantes", jPanel1);

        jPanel2.setBackground(new java.awt.Color(122, 185, 185));

        jTableAsignatura.setBackground(new java.awt.Color(235, 245, 251));
        jTableAsignatura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Asignatura", "id_curso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAsignatura.setRowHeight(20);
        jScrollPane1.setViewportView(jTableAsignatura);

        btnRetirar1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnRetirar1.setText("Retirar");
        btnRetirar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirar1ActionPerformed(evt);
            }
        });

        btnAgregar1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnAgregar1.setText("Inscribir");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Asiganaturas disponibles ");
        jLabel6.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar1)
                .addGap(18, 18, 18)
                .addComponent(btnRetirar1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetirar1)
                    .addComponent(btnAgregar1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
        );

        jTabCurso.addTab("Asignaturas", jPanel2);

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save_close.png"))); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel7.setText("Capacidad");

        tCapacidad.setForeground(new java.awt.Color(0, 0, 255));
        tCapacidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setText("Año");

        tNombreDocente.setEditable(false);
        tNombreDocente.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tNombreDocente.setForeground(new java.awt.Color(0, 153, 51));
        tNombreDocente.setDisabledTextColor(new java.awt.Color(0, 153, 51));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setText("Docente");

        tAnio.setEditable(false);
        tAnio.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tAnio.setForeground(new java.awt.Color(0, 153, 51));
        tAnio.setDisabledTextColor(new java.awt.Color(0, 153, 51));

        btnDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/binoculars.png"))); // NOI18N
        btnDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabCurso)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarSeleccionado3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTanda, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tAula, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tAnio)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tCapacidad))
                                    .addComponent(cbGrado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tNombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(tAula, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTanda, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDocente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tNombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarSeleccionado3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Estas seguro que deseas borrar la asignatura de este curso ?",
                "Borrado de asignatura del curso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            DefaultTableModel mod = (DefaultTableModel) jTableEstudiante.getModel();
            mod.removeRow(jTableEstudiante.getSelectedRow());
        }
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        FrmBuscarEstudiante bEstudiante = new FrmBuscarEstudiante(this, true);
        bEstudiante.setLocationRelativeTo(null);
        bEstudiante.setVisible(true);

        if (bEstudiante.confirmarSeleccion > 0) {
            DefaultTableModel model = (DefaultTableModel) jTableEstudiante.getModel();
            int codEstudiante = Integer.parseInt(String.valueOf(bEstudiante.jTableEstudiante.getValueAt(bEstudiante.jTableEstudiante.getSelectedRow(), 0)));
            String nombreEstudiante = String.valueOf(bEstudiante.jTableEstudiante.getValueAt(bEstudiante.jTableEstudiante.getSelectedRow(), 1));

            model.addRow(new Object[]{codEstudiante, nombreEstudiante});
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarSeleccionado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSeleccionado3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnEliminarSeleccionado3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (tAula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Favor ingresar el aula");
            return;
        }
        if (tAnio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione la fecha de inicio del año escolar");
            return;
        }
        
        if (this.idDocente==0) {
            JOptionPane.showMessageDialog(this, "Seleccione el docente de este curso");
            return;
        }

        setCurso();

        if (c.getId_curso() == 0) {
            long idCurso = dc.setInsertarCurso(c);
            if (jTableAsignatura.getRowCount() > 0) {
                agregarAsignatura(idCurso);
            }

            if (jTableEstudiante.getRowCount() > 0) {
                inscribirEstudiante(idCurso);
            }

            if (idCurso > 0) {
                JOptionPane.showMessageDialog(this, "El curso ha sido registrado correctamente");
            }
        }

        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tFechaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFechaKeyReleased

    }//GEN-LAST:event_tFechaKeyReleased

    private void tFechaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tFechaComponentAdded


    }//GEN-LAST:event_tFechaComponentAdded

    private void tFechaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tFechaPropertyChange
        int anio = FormatoFecha.getAnio(tFecha);
        tAnio.setText(String.valueOf(anio + "-" + (anio + 1)));

    }//GEN-LAST:event_tFechaPropertyChange

    private void jTabCursoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabCursoStateChanged

    }//GEN-LAST:event_jTabCursoStateChanged

    private void jTabCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabCursoMouseClicked
        if (jTabCurso.getSelectedIndex() == 0) {
            btnAgregar.setText("Inscribir");
        } else {
            btnAgregar.setText("Agregar");
        }
    }//GEN-LAST:event_jTabCursoMouseClicked

    private void btnRetirar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirar1ActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Estas seguro que deseas borrar la asignatura de este curso ?",
                "Borrado de asignatura del curso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            DefaultTableModel mod = (DefaultTableModel) jTableAsignatura.getModel();
            mod.removeRow(jTableAsignatura.getSelectedRow());
        }
    }//GEN-LAST:event_btnRetirar1ActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void btnDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocenteActionPerformed
        FrmBuscarEmpleado docente = new FrmBuscarEmpleado(this, true);
        docente.setLocationRelativeTo(null);
        docente.setVisible(true);

        if (docente.confirmarSeleccion > 0) {

            this.idDocente = Integer.parseInt(String.valueOf(docente.jTableEmpleado.getValueAt(docente.jTableEmpleado.getSelectedRow(), 0)));
            String nombreDocente = String.valueOf(docente.jTableEmpleado.getValueAt(docente.jTableEmpleado.getSelectedRow(), 1));

            tNombreDocente.setText(nombreDocente);
        }

    }//GEN-LAST:event_btnDocenteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnDocente;
    private javax.swing.JButton btnEliminarSeleccionado3;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnRetirar1;
    private javax.swing.JComboBox<String> cbGrado;
    private javax.swing.JComboBox<String> cbTanda;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabCurso;
    private javax.swing.JTable jTableAsignatura;
    private javax.swing.JTable jTableEstudiante;
    private javax.swing.JScrollPane jspDatos;
    public javax.swing.JLabel lbTitulo;
    public javax.swing.JPanel pnTitulo;
    private javax.swing.JTextField tAnio;
    public javax.swing.JTextField tAula;
    private javax.swing.JFormattedTextField tCapacidad;
    private com.toedter.calendar.JDateChooser tFecha;
    private javax.swing.JTextField tNombreDocente;
    // End of variables declaration//GEN-END:variables

    private void setCurso() {
        c.setAula(tAula.getText().trim());
        c.setCapacidad(validarIntegerTexto(tCapacidad));
        c.setTanda(cbTanda.getSelectedIndex());
        c.setGrado(cbGrado.getSelectedIndex());
        c.setAnioEscolar(tAnio.getText());
        c.setNombreGrado(String.valueOf(cbGrado.getSelectedItem()));
        c.setNombreTanda(String.valueOf(cbTanda.getSelectedItem()));
        c.setIdDocente(this.idDocente);

    }

    private int validarIntegerTexto(JFormattedTextField f) {
        int valor = 0;
        try {
            valor = Integer.parseInt(String.valueOf(f.getText()));
        } catch (NumberFormatException e) {
        }

        return valor;
    }

    private void cargarAsignaturas() {
        ArrayList datos = dbAsignatura.todasLasAsignatura();
        DefaultTableModel model = (DefaultTableModel) jTableAsignatura.getModel();
        model.setNumRows(0);
        datos.forEach(obj -> {
            model.addRow((Object[]) obj);
        });
    }

    private void cargarAsignaturaDelCuso(int id_curso) {
        ArrayList datos = dbAsignatura.asignaturasDelCurso(id_curso);
        DefaultTableModel model = (DefaultTableModel) jTableAsignatura.getModel();
        model.setNumRows(0);
        datos.forEach(obj -> {
            model.addRow((Object[]) obj);
        });
    }

    private void agregarAsignatura(long idCurso) {
        int filas = jTableAsignatura.getRowCount();
        for (int i = 0; i < filas; i++) {
            dc.setRegistroAsignaturaEnCuso(idCurso, Integer.parseInt(String.valueOf(jTableAsignatura.getValueAt(i, 0))));
        }
    }

    private void inscribirEstudiante(long idCurso) {
        int filas = jTableEstudiante.getRowCount();
        for (int i = 0; i < filas; i++) {
            dc.setRegistroEstudianteEnCuso(idCurso, Integer.parseInt(String.valueOf(jTableEstudiante.getValueAt(i, 0))));
        }
    }

    private void formatoRejilla() {
        //Tabla de estudiante
        TableColumnModel columnModel = jTableEstudiante.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(10);
        columnModel.getColumn(1).setPreferredWidth(420);
        columnModel.getColumn(2).setPreferredWidth(0);
        columnModel.getColumn(2).setMinWidth(0);
        columnModel.getColumn(2).setMaxWidth(0);
        jTableEstudiante.setColumnModel(columnModel);
        jTableEstudiante.getTableHeader().setReorderingAllowed(false);

        //Tabla de asignatura
        TableColumnModel colModel = jTableAsignatura.getColumnModel();
        colModel.getColumn(0).setPreferredWidth(10);
        colModel.getColumn(1).setPreferredWidth(420);
        colModel.getColumn(2).setPreferredWidth(0);
        colModel.getColumn(2).setMinWidth(0);
        colModel.getColumn(2).setMaxWidth(0);

        jTableAsignatura.setColumnModel(colModel);
        jTableAsignatura.getTableHeader().setReorderingAllowed(false);

    }

}
